### ISSUE TITLE
Visibility of state icons using Firefox vs. Chrome

### ISSUE THREAD

**Issue by bjfiedler** [thm-projects/frag.jetzt#4]
Hi,

the question cards on the question overview show different behaviour using Firefox and Chrome.
Firefox doesn't show them, just the burger menu. Therefore, the actions are reachable, but the state isn't visible.

Firefox:
![grafik](https://user-images.githubusercontent.com/5951570/95307946-8fbcf800-0889-11eb-8560-c035ca752617.png)

Chrome:
![Screenshot from 2020-10-07 10-41-58](https://user-images.githubusercontent.com/5951570/95308126-c3981d80-0889-11eb-95c3-d6b51f8b2bb2.png)

**Comment by bjfiedler** [comment]
Sorry for the inconvenience, my colleages just told me its just my Firefox and an update fixed the problem.

**Comment by tekay** [comment]
:D Nothing to worry about, thanks for posting the solution!
