### ISSUE TITLE
"Delete questions" deletes room instead

### ISSUE THREAD

**Issue by schirmeier** [thm-projects/frag.jetzt#5]
Steps to reproduce:
- In the "creator" role, click on one of your rooms.
- Top-right corner, click "Options", then "Delete questions" (in order to reset the room).

Actual result:
- "Are you sure? Do you really want to delete the room XY? [...]", button "Delete room" is shown.
- After clicking the button, room gets deleted.

Expected result:
- After confirmation, the room still exists, all questions are gone.

**Comment by kqc-real** [comment]
Fixed. Thank you for pointing out the issue to us.
