### ISSUE TITLE
Room creation broken

### ISSUE THREAD

**Issue by schirmeier** [thm-projects/frag.jetzt#6]
Steps to reproduce:
- In Firefox (FF 93.0 on Ubuntu Linux in my case) or Google Chrome, click "(+) Create a room" on the start page.
- Enter a room name. Click "Create room".

Actual result:
- A lot of error messages in dark red boxes pop up in quick succession.
- The start page is shown as if the action had failed.
- In fact, the room is created, and shows up in the creator's room list.

Expected result:
- Room is created, and the page switches to the room list containing the new room.

**Comment by kqc-real** [comment]
Not reproducible in Firefox on macOS. If the error persists, please open an issue again.
